export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const ERROR = "ERROR"
export const CREATE_ART = "CREATE_ART"
export const GET_ALL_ART = "GET_ALL_ART"
export const GET_ARTIST = "GET_ARTIST"
export const UPDATE_ARTIST = "UPDATE_ARTIST"
